version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building static site..."
      - aws s3 sync . s3://$WEBSITE_BUCKET --delete
artifacts:
  files:
    - '**/*'

